spring.application.name=conta-bancaria
# Configurações do banco de dados H2
spring.datasource.url=jdbc:h2:mem:conta-bancaria-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Configurações do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
